# Generated by Django 5.0.3 on 2024-05-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_department',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_image',
            field=models.ImageField(default='', upload_to='imageFolder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_role',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_salary',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_email',
            field=models.EmailField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_location',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_phone',
            field=models.CharField(default='', max_length=15),
        ),
    ]
