# Generated by Django 5.0.6 on 2024-05-13 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_remove_employee_employee_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='id',
            new_name='eid',
        ),
    ]
