# Generated by Django 5.0.6 on 2024-05-13 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_rename_id_employee_eid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='eid',
            new_name='id',
        ),
    ]
