# Generated by Django 5.0.6 on 2024-05-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_alter_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_bonus',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_education',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_location',
            field=models.CharField(default='', max_length=400),
        ),
    ]
